from tkinter import *
from gui.button.back import *
from gui.template.data import *
from gui.template.hide import *
from gui.template.show import *
from gui.template.test import *
from gui.template.msg import *
from gui.template.duplicate import *
from gui.image.btn_start import *
